logging:
  level:
    ru:
      practicum:
        shareit: info
server:
  port: 9090
  datasource:
    driverClassName: org.h2.Driver
    password: test
    url: jdbc:h2:mem:shareit
    username: test
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
spring:
  banner:
    location: banner-test.txt
